### ISSUE TITLE
AADM Storage in KB and deployment: manage of Interface implementation scripts

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/ide#1]
Feature:
During the storage of the AADM model into the KB, and/or the AADM deployment into the Sodalite backend, the IDE should prompt the user to provide the content of every implementation script required by the interfaces of the types used by the templates nodes included in the AADM.

Procedure:
- AADM Editor should ask the KB for the implementation names of every operation declared in the types hierarchy of templates declared in the AADM

- For each, implementation, the IDE user is prompted to provide that implementation file from her filesystem.
- Upon saving the AADM into the KB and/or deploying it into the Sodalite backend, all these implemetation files will be sent within the REST invocation to the remote component

Dependencies:
1. KB Reasoner REST API for saving AADM should accept all these implementation files in a multipart-form POST message
2. IaC Deployment REST API should accept all these implementation files in a multipart-form POST message

@gmeditsk: please, provide functional specification from KB perspective
@dradX : please, provide functional specification from IaC perspective

**Comment by gmeditsk** [comment]
Thanks Yosu. I think we should further discuss this, since I am not sure that I understand what needs to be implemented and what is required from the KB. Perhaps an example or the association of this feature with a requirement would help.

**Comment by jesus-gorronogoitia** [comment]
Kalimera @gmeditsk Yes, we need to ask examples to UC providers. The imperative Tosca workflow specification is available [here](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969481)

**Comment by jesus-gorronogoitia** [comment]
This feature has been implemented in #15 and #14

**Comment by jesus-gorronogoitia** [comment]
Incorporate a optional relative path for each implementation script, including the primary and the dependencies

**Comment by jesus-gorronogoitia** [comment]
Relative path added to RM grammar, and Turtle serialization
