### ISSUE TITLE
Pop-up fixes when deployment failure occurs

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#110]
IDE returns a blueprint token and a session token, when a deployment failure occurs.

![Screenshot from 2021-03-11 12-18-03](https://user-images.githubusercontent.com/2138519/110780603-2b052f80-8265-11eb-8503-0f9bd153d050.png)

However, xopera-rest-api does not use these notations anymore, and it creates a confusion which token to use for debugging, e.g. to get [the deployment status in xopera-rest-api](https://github.com/SODALITE-EU/xopera-rest-api#obtain-deployment-status) we should use deployment id, which is not displayed in the pop-up. Preferred output should be mapped into:
```
blueprint token -> blueprint ID
session token -> deployment ID
```

Additionally, it would be useful to enable a selection of the content of the pop-up, since it is currently not possible to select and copy tokens and is inconvenient to retype them.

**Comment by jesus-gorronogoitia** [comment]
I will fix the message notation. Regarding the second point, selection in message dialog is not possible so the message is already copied in the clipboard, you just need to paste it.
