### ISSUE TITLE
Support SODALITE Image-Builder API 1.0.0

### ISSUE THREAD

**Issue by mihaTrajbaric** [SODALITE-EU/ide#117]
Image-builder API has received some minor changes with the intent to simplify it and increase commonality  with other SODALITE APIs (xOpera REST API, PDS,...) 
## Resources: 
- [openapi-spec.yaml](https://github.com/SODALITE-EU/image-builder/blob/0ec4a0b1639b12847b93dfbf49e1f0dcd7b2fa98/openapi-spec.yml)
- [requests.http](https://github.com/SODALITE-EU/image-builder/blob/307bf2101a06dd64e2f8fb6bf5e581b5a58f1947/api-calls.http)
- [BuildParams](https://github.com/SODALITE-EU/image-builder/tree/307bf2101a06dd64e2f8fb6bf5e581b5a58f1947/src/image_builder/TOSCA/playbooks/tests/tests-json)
- live instance: http://192.168.2.70:5000/
- API docs on live instance (OpenAPI UI): http://192.168.2.70:5000/ui/

## API usage
I will be using this set of [BuildParams](https://github.com/SODALITE-EU/image-builder/blob/307bf2101a06dd64e2f8fb6bf5e581b5a58f1947/src/image_builder/TOSCA/playbooks/tests/tests-json/test_02_no_context.json) (a.k.a image descriptor) to build simple docker-image
### Start build job
Image-building job (Invocation) is requested using /build endpoint. Endpoint accepts the BuildParams and returns the invocation_id.
```shell script
curl -X POST "http://192.168.2.70:5000/build/" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"source_type\":\"dockerfile\",\"source_url\":\"https://raw.githubusercontent.com/mihaTrajbaric/image-builder-test-files/master/no_context/Dockerfile\",\"target_image_name\":\"tests/no_context\",\"target_image_tag\":\"latest\"}"
```
returns: 
```json
{
  "invocation_id": "849d9c43-79c8-46fc-b9c6-e4f178a70b9d"
}
```
and `status_code = 202`

### Check job status
To check image building job status, users can use invocation_id, obtained from /build endpoint, and call /status/{invocation_id} endpoint:
```shell script
curl -X GET "http://192.168.2.70:5000/status/849d9c43-79c8-46fc-b9c6-e4f178a70b9d" -H  "accept: application/json"
```

during building, the response will look like this:

```json
{
  "build_params": {
    "source_type": "dockerfile",
    "source_url": "https://raw.githubusercontent.com/mihaTrajbaric/image-builder-test-files/master/no_context/Dockerfile",
    "target_image_name": "tests/no_context",
    "target_image_tag": "latest"
  },
  "invocation_id": "849d9c43-79c8-46fc-b9c6-e4f178a70b9d",
  "response": "",
  "state": "in_progress",
  "timestamp_start": "2021-03-17T10:39:14.824459+00:00",
  "timestamp_submission": "2021-03-17T10:39:14.816626+00:00"
}
```
and status_code = 200

when building is over, response will look like this:

```json
{
  "build_params": {
    "source_type": "dockerfile",
    "source_url": "https://raw.githubusercontent.com/mihaTrajbaric/image-builder-test-files/master/no_context/Dockerfile",
    "target_image_name": "tests/no_context",
    "target_image_tag": "latest"
  },
  "invocation_id": "849d9c43-79c8-46fc-b9c6-e4f178a70b9d",
  "response": "[Worker_0]   Deploying my-workstation_0\n[Worker_0]   Deployment of my-workstation_0 complete\n[Worker_0]   Deploying image-builder_0\n[Worker_0]     Executing create on image-builder_0\n[Worker_0]   Deployment of image-builder_0 complete\n",
  "state": "success",
  "timestamp_end": "2021-03-17T10:39:27.589999+00:00",
  "timestamp_start": "2021-03-17T10:39:14.824459+00:00",
  "timestamp_submission": "2021-03-17T10:39:14.816626+00:00"
}
```

and status_code = 200

#### Keys in Invocation object
Invocation object (returned by /status endpoint) has following keys:
- `"build_params"`:  copy of build_params, sent to API with call to /build enpoint
- `"invocation_id`: id of invocation, sent as part of request to /status endpoint
- `"response"`: stacktrace of image-building invocation. Usefull for debugging in case of failure
- `"state"`: one of (pending, in_progress, success, failed)
- `"timestamp_submission"`: timestamp of submitting image-building job
- `"timestamp_start"`: timestamp of when image-builder took job from queue and started building image
- `"timestamp_end"`: timestamp of the time when job was done (with success or failure)
#### Status codes for /status endpoint
- 200: invocation found (in any state)
- 404: invocation not found (does not exist)

### Check logs
Endpoint /log has been deprecated due to merge of functionality between old /info/status and /info/log enpoints into new /status enpoint.

**Comment by jesus-gorronogoitia** [comment]
Feature implemented in IDE, in commit https://github.com/SODALITE-EU/ide/commit/10d4d645edc8ab2130d0af72bf5a2904778e934e
PR created and merged in master.
Tested in IDE, using provided build_image descriptor example. ImageBuilder correctly invoked. After several status iterations (on building status) a failed status is reported, I assume because that image is already created. 
I cannot build a new IDE update site as Jenkins is down. Once Jenkins is restored, I will create create a new update site for the IDE and let you know, so you can test it.

**Comment by mihaTrajbaric** [comment]
Hi Yosu, that's good to hear.

Image builder does not fail if image already exists, it should still be a success. The reason for the failure you were experiencing was that docker registry, which image-builder targets, was down.

I restarted it so image-builder should finish with success now.

Looking forward to testing this integration!

**Comment by mihaTrajbaric** [comment]
Integration works, I think we can close this issue
