### ISSUE TITLE
Integration with Platform Discovery Service

### ISSUE THREAD

**Issue by dradX** [SODALITE-EU/ide#118]
Integration with Platform Discovery Service.
## Resources: 
- [openapi-spec.yaml](https://github.com/SODALITE-EU/platform-discovery-service/blob/master/openapi-spec.yaml)
- [usage](https://github.com/SODALITE-EU/platform-discovery-service#usage)
- live instance: http://http://192.168.2.178:8089/
- API docs on live instance (OpenAPI UI): http://http://192.168.2.178:8089/ui/

## API usage
PDS offers to routes - discover/ and update/ - update should be used to save the TOSCA model to the knowledge base. 

Sample payload for the call for Openstack platform type
```json
{
    "inputs" : 
    {
    	"os_env": {
		    "OS_AUTH_URL": "http://stackdashboard.sodalite.eu:5000",
		    "OS_PROJECT_ID": "8a1a7649c3a44f16a70361b485389340",
		    "OS_PROJECT_NAME": "orchestrator",
		    "OS_USER_DOMAIN_NAME": "Default",
		    "OS_PROJECT_DOMAIN_ID": "default",
		    "OS_REGION_NAME": "RegionOne",
		    "OS_USERNAME": "username",
		    "OS_PASSWORD": "password",
		    "OS_INTERFACE": "public",
		    "OS_IDENTITY_API_VERSION": 3,
		    "OS_TENANT_ID" : "",
			"OS_TENANT_NAME" : ""
    	}
    },
    "namespace": "TestOpenstack",
    "platform_type" : "openstack"
}
```

This implies the IDE should provide the possibility to enter three fields to setup the call `inputs`, `namespace` and `platform_type`. 
IDE supplies the call header with a valid access token.

**Comment by jesus-gorronogoitia** [comment]
Hi @dradX please clarify the following aspects:
- Who (role) may request to invoke PDS from the IDE?
- What is the IDE circumstance under which that role may want to invoke the PDS?. I assume invoking PDS is independent from any other SODALITE process triggered from the IDE, so that invoking the PDS can be trigger from the general Sodalite Menu
- I assume the IDE will provide a wizard that requests users to provide the following entries: inputs, namespace, platform_type. What are the types and range of possible values for those entries?. I assume namespace and platform_type are strings. Are they selected from a list of possible values? What about inputs type? Are they taken from an inputs file? Your example structure looks like JSON, so I assume inputs will be provided by the user from a file. There is no way to provide a wizard form to provide such JSON-based structure.
- What is the PBS should the IDE wizard invoke? /update or /discover
- Is there any returned value that should be reported to the user? Or only the success or failure of the request?

**Comment by dradX** [comment]
Hi @jesus-gorronogoitia 

Thanks for the questions I have added answers below: 
-   Who (role) may request to invoke PDS from the IDE?
-- A1)  A Resource Expert role is the one that might trigger this, should have the `rm-write` permissions to store to the KB.
- What is the IDE circumstance under which that role may want to invoke the PDS?. I assume invoking PDS is independent from any other SODALITE process triggered from the IDE, so that invoking the PDS can be trigger from the general Sodalite Menu
-- A2) Yes, it is independent. 
- I assume the IDE will provide a wizard that requests users to provide the following entries: inputs, namespace, platform_type. What are the types and range of possible values for those entries?. I assume namespace and platform_type are strings. Are they selected from a list of possible values? What about inputs type? Are they taken from an inputs file? Your example structure looks like JSON, so I assume inputs will be provided by the user from a file. There is no way to provide a wizard form to provide such JSON-based structure.
-- A3) payload: 
--- `inputs` is provided by the user, should have a JSON structure as shown in the example might be taken from a file (not expecting a wizard for this)
--- `namespace` is an alphanumeric string 
--- `platform_type` is a string from list: `slurm`,`torque`, `openstack`, `aws`, `kubernetes`
- What is the PBS should the IDE wizard invoke? /update or /discover
-- A4) Please invoke `/update` this will save the result to the KB. 
- Is there any returned value that should be reported to the user? Or only the success or failure of the request?
-- A5) Only the result of the call is shown for now as we have in the response.

**Comment by jesus-gorronogoitia** [comment]
Are these three inputs mandatory? If not, which ones are?

**Comment by jesus-gorronogoitia** [comment]
Is AIM token in request header required? Still unclear to me the returned type, and the returned HTTP codes, I need both to be able to parse the response

**Comment by dradX** [comment]
All the fields are mandatory as they describe the access and the returned values e.g. the definition of the resources in the result as they will be stored in the KB. Additionally, the access token is required in the header to check authorization in PDS.

**Comment by jesus-gorronogoitia** [comment]
Feature implemented in commit https://github.com/SODALITE-EU/ide/commit/4e745e7d5d7400417eb0c318205a8bd29028f390

PDS update can be accessed from any Project explorer contextual menu
![image](https://user-images.githubusercontent.com/3658315/112186032-0c0d8280-8c01-11eb-8e0e-942788add562.png)

or from the new Eclipse top menu for Sodalite
![image](https://user-images.githubusercontent.com/3658315/112186130-23e50680-8c01-11eb-8117-9015fbafae49.png)

In both cases, this wizard is launched,
![image](https://user-images.githubusercontent.com/3658315/112186351-53940e80-8c01-11eb-90b2-84cdc16135c6.png)

Upon filling in the wizard form, the PDS update API is requested. Upon completion, the user is informed with a dialog

This feature will be ready to be tested once Jenkins is available and I can launch the IDE job to update the IDE update site

If you need me to change any labeling in the Wizard and/or Sodalite menu (including tooltips) let me know
