### ISSUE TITLE
Not getting recommendations for requirements

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#120]
I installed the SODALITE plugin according to instructions [here](https://github.com/SODALITE-EU/ide).
I cannot get requirement recommendations by clicking ctrl + space keys:
![Capture](https://user-images.githubusercontent.com/6237917/112132304-1fa1f480-8bd3-11eb-88d6-98a47a36c7b3.PNG)

### Environment
**java version**
```
C:\Users\USER>java -version                                                                                            
 java version "11.0.9" 2020-10-20 LTS  Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)                                                               Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)  
```
**OS: windows 10**

**Comment by jesus-gorronogoitia** [comment]
Please, show me your Eclipse preference page for Sodalite backend endpoints (Go to menu Window/Preferences, then search for Sodalite)

![image](https://user-images.githubusercontent.com/3658315/112188342-33fde580-8c03-11eb-824f-e0670a104231.png)

and for Sodalite user account

![image](https://user-images.githubusercontent.com/3658315/112188451-4bd56980-8c03-11eb-9481-82461d8d96e3.png)

**Comment by jesus-gorronogoitia** [comment]
Works for me, but it is a bit slow (more than 5 seconds to pop up)
![image](https://user-images.githubusercontent.com/3658315/112189082-ecc42480-8c03-11eb-8903-d9a89838ea14.png)

**Comment by jesus-gorronogoitia** [comment]
I tried against CERTH KB, I haven't test with Testbed KB

**Comment by zoevas** [comment]
Hello Yosu,

Thanks for the instructions.

I am also using certh server

### Preferences:

![preferences](https://user-images.githubusercontent.com/6237917/112202440-0f613800-8c1a-11eb-95b9-4dee34669501.PNG)
### user account
IAM is off on certh, so I think we are ok with this set up
![user account](https://user-images.githubusercontent.com/6237917/112202459-15efaf80-8c1a-11eb-943f-4eacfa080e0b.PNG)

**_I get an error missing RULE ID at "_**
![requirements](https://user-images.githubusercontent.com/6237917/112202529-2738bc00-8c1a-11eb-8365-70fcba960ddc.PNG)


I need to have an ide working for providing a video in the snow use case partners for the demo. 
But  if we see that my ide set up needs time to be fixed, since I suppose it might be difficult to help since you are not using windows 10, if it is easy for you, we can prepare a video with your ide together. 

Thanks,
Zoe

**Comment by jesus-gorronogoitia** [comment]
Let's wait for fixing Jenkins to build the update site, so you can update the IDE and try again, as with your configuration my IDE works well on this issue. Meantime, I will try to find a Windows VM where to test and debug this issue

**Comment by jesus-gorronogoitia** [comment]
I've manually created a new update site for the IDE, so you can update the IDE and check this issue again. If still failing, please check the Error Log View and reported me if an exception for this issue is shown

**Comment by jesus-gorronogoitia** [comment]
fixed in commit https://github.com/SODALITE-EU/ide/commit/d1c6c034cb3ecdfbc564ed2b214fe341db2d64cd
Please update IDE and check

**Comment by jesus-gorronogoitia** [comment]
Wrong KB Reasoner endpoint in Sodalite Backend preferences page. Preventing IDE failure in case of adding blanks to endpoints or not ending then in /

**Comment by jesus-gorronogoitia** [comment]
fix committed in https://github.com/SODALITE-EU/ide/commit/c8502bfb8c1aa3afae42e547e9c6cbd786dbd694
