### ISSUE TITLE
Add deployment ID in the pop-up once deployment is successfully completed

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#121]
# Current state
Once deployment is completed successfully, blueprint ID is shown, but there is no way to obtain the deployment ID needed e.g. for redeployment.
![Screenshot from 2021-03-23 14-57-55](https://user-images.githubusercontent.com/2138519/112159056-07d56b00-8be9-11eb-9d02-f351e1781905.png)

# Desired state
The pop-up displays also the deployment ID, and the blueprint and deployment IDs are copied to the clipboard.

**Comment by jesus-gorronogoitia** [comment]
Fix in commit https://github.com/SODALITE-EU/ide/commit/28500596836ba0dfdfd1092028754e00176aef11
As soon as Jenkins is back, I will lauch the IDE job so you can update your IDE from the update site and test this patch.

**Comment by jesus-gorronogoitia** [comment]
Please, update the IDE, and check if this issue has been solved. If so, please, close it

**Comment by kmlTE** [comment]
Thank you, Yosu. It is fixed!
