### ISSUE TITLE
Models created via saveTOSCA Reasoner endpoint are not reflected in KB browser view

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#124]
## Prerequisites

1. A namespace created via saveTOSCA method exists in KB
2. Namespace contains both RMs and AADMs
3. User has read/write rights to both RMs and AADMs for this namespace

## Current behaviour
This namespace is not reflected in KB browser view. Its name is returned by `/reasoner-api/v0.6/namespace` endpoint but  `/reasoner-api/v0.6/models` endpoint does not return any data neither for `type=RM` nor for `type=AADM`. If a user saves a model into this namespace via IDE and refreshes KB the new model appears in the browser. (I assume that the issue is with the filename attached to the model. Models created via saveTOSCA do not have it)

## Expected behaviour
Models created via saveTOSCA Reasoner endpoint are shown in KB browser view

**Comment by jesus-gorronogoitia** [comment]
So, models created by users are reflected in the KB Browser View (after refreshing it) but not for models created by PDS? If so, this issue should be managed by @zoevas

**Comment by zoevas** [comment]
I fixed it. Indeed it was related with DSL and file name not attached in PDS models. I ll deploy it on the CERTH server.

Manual deployment takes time on the testbed (upload of 0.7 GB image is slow). I ll do it next week.

**Comment by zoevas** [comment]
I think that this has been fixed. So it can be closed.
