### ISSUE TITLE
Warnings (smells and bugs) not showed in IDE

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#134]
I added some bugs/smells in snow uc on **CERTH** server. While in _/saveAADM_ response reasoner logs, the warnings are present,
the warnings do not appear in IDE, after the _saveAADM_ completes.
Should I set any configuration in IDE?

> {
  "warnings": [
    {
      "type": "InvalidIPAddressBinding",
      "info": {
        "name": "ports",
        "context": "snow-security-rules",
        "element_type": "Property",
        "description": "The address has a binding of 0.0.0./*L"
      }
    },
    {
      "type": "InvalidPortRange",
      "info": {
        "name": "exposed_ports",
        "context": "snow-mysql",
        "element_type": "Property",
        "description": "TCP port values are not within the range from 0 to 65535."
      }
    },
    {
      "type": "AdminByDefault",
      "info": {
        "name": "username",
        "context": "snow-vm",
        "element_type": "Property",
        "description": "The default user is admin or root"
      }
    },
    {
      "type": "HardcodedSecret",
      "info": {
        "name": "username",
        "context": "snow-vm",
        "element_type": "Property",
        "description": "The password or user name is hardcoded"
      }
    }
  ]
}

### The bugs in the snow DSL:
_AdminByDefault_ and _HardCodedSecret_ in username property
![AdminByDefault](https://user-images.githubusercontent.com/6237917/113403549-82ec0d80-93af-11eb-9d4c-d36af5349390.png)

InvalidPortRange in exposed_ports property

![exposed_ports](https://user-images.githubusercontent.com/6237917/113403707-c21a5e80-93af-11eb-8469-cd70ffc65ba6.png)

_InvalidIPAddressBinding_ in ports property
![remote_ip_prefix](https://user-images.githubusercontent.com/6237917/113403683-b890f680-93af-11eb-85c1-bbf3d29efeb8.png)

**Comment by jesus-gorronogoitia** [comment]
Kalimera @zoevas I confirm this issue. Working on fixing it.

**Comment by jesus-gorronogoitia** [comment]
Fix in commit https://github.com/SODALITE-EU/ide/commit/2568fa12addb135b8e10ba5ae1e15831116981b0
I will publish a new IDE update site. Please, update IDE and check

**Comment by zoevas** [comment]
Done.
