### ISSUE TITLE
Save AADM: send associated files (e.g. autotuning, Ansible playbooks) within ADDM TTL to the KB

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/ide#15]
When the user save an model (ie. RM,  AADM, OM) into the KB, it should sent as well all the associated external files attached to the model:
- Autotuning model in the optimization model
- The optimization model in the AADM
- Implementation primary and dependencies (e.g. Ansible playbooks) for operations of interfaces of node types in RMs.

This requires KB API to support the reception of these additional files, identified within the model by name.
For each referenced file, the TTL serialization generates two parameters:
- a path parameter with the user's local filesystem path 
- a content parameter with the raw content of the file as a string, where all (new line character) have been replaced with /n, as the KB does not support the inclusion of new lines in that content

**Comment by zoevas** [comment]
Do you mean that, for example optimization DSL, along with the aadmTTL in saveAADM request, an optimizationTTL will be sent ?
skyline_extractor:
  optimizations: <here this is a file that would be sent seperately from the aadm?>

**Comment by jesus-gorronogoitia** [comment]
This has to be discussed, this issue does not refer to the optimization model, which can be provided embedded within the AADM TTL or attached as another TTL. This issue refers to the autotuning model and Ansible playbooks, which are provided as they are, not serialized in TTL because they are not injected into the KB with their structure, but as plain text associated to a AADM property. These models will be passed (by the KB) to IaC Builder and Optimizer as plain text in turn.

**Comment by jesus-gorronogoitia** [comment]
The fact the optimization model is referenced in the AADM or embedded therein is only an IDE issue. When the IDE sends the saveAADM request to the KB, it can provide two separate TTL (AADM and Optimization) or just one, as you prefer.

**Comment by zoevas** [comment]
Regarding autotuning DSL, I understand that  ide will send external files as a parameters to saveAADM  e.g. autotuningDSL  "plain text"
The  IaC subsystem will request from reasoner both the file name and the content file?

If yes, then in the modeling part, we should find a way to associate both the filename and the 
content file with the node template.

**Comment by jesus-gorronogoitia** [comment]
External files such as Ansible playbooks are plain text files referenced within the AADM, which can be serialized with the Turtle format, by injecting the file content.
However, in order to test implementation, I need the scripts associated to the Snow UC to be referenced in the Snow RM and saved in the KB

**Comment by jesus-gorronogoitia** [comment]
Hi @dradX Please, confirm that in resource models and AADM models the implementations (i.e. scripts) of operations associated to interfaces of types and templates needs to be provided by the REs and AOEs when the models are saved into the KB as plain text scripts (e.g. Ansible playbooks). If so, I will need those implementations for Snow and other UCs.

**Comment by jesus-gorronogoitia** [comment]
See #23 for the implementation scripts (Ansible playgrounds) for Sodalite use cases

**Comment by jesus-gorronogoitia** [comment]
This feature is also associated to #14

**Comment by jesus-gorronogoitia** [comment]
Implemented support (branch issue_15) for:
- Autotuning model in the optimization model
- The optimization model in the AADM - Current implementation uses JSON serialization (pending to decide if adopt Turtle as requested by the KB Reasoner)
- Implementation primary for operations of interfaces of node types in RMs.

**Comment by jesus-gorronogoitia** [comment]
Fixed some issues. Models in #23 have been saved, including AADMs and RMs
