### ISSUE TITLE
Resume deployment from a failed component

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#158]
SODALITE IDE should support a resume of a deployment from a failed component after the deployment is failed.  

xOpera REST API provides an API that allows to resume the deployment from the failed component. This API call should be a POST request and should accept the following parameters:
- Deployment ID
- Number of workers for parallel execution
- A "clean state" flag to restart the deployment from the beginning
- Inputs file

The OpenAPI description is provided [here](https://github.com/SODALITE-EU/xopera-rest-api/blob/master/openapi-spec.yml#L1097), where specifics of the POST request and response codes are described, and below is an example taken from [a list of HTTP API calls examples](https://github.com/SODALITE-EU/xopera-rest-api/blob/master/api-calls.http#L221) for xOpera REST API:

```
curl -X POST "http://localhost:8080/deployment/854cc717-fd02-4c51-a35d-7223f9fc8423/deploy_continue?workers=10&clean_state=false" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
```

**Comment by jesus-gorronogoitia** [comment]
Hi @kmlTE this feature has been implemented as part of the feature #10 It will be released by today for testing, but requires new deployments are executed with new deployment wizard and process support, as well implemented and released within this feature.
