### ISSUE TITLE
Add support for grafana-registry

### ISSUE THREAD

**Issue by jramosrivas** [SODALITE-EU/ide#159]
To register deployments in grafana and create dashboards registered to the user that creates the deployment, a call needs to be made to the new grafana-registry component (API). All the calls to this new component are secured with JWT authorization.

Example curl calls (tokens have been shortened here):

- Create dashboards: 
`curl 192.168.3.74:3001/dashboards -X POST -d '{"deployment_label":"test-sec","monitoring_id":"as54d5a-trvb2yh58-dsada9s5fd8f"}' -H'Content-Type: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA...eQQ76mK9vDG9WmeJ44lbhDtbEDMzKsbA6QKvs6xFk2RRRL2VHF9iG21xSO5AIU-VcJEc7uQNZkwNwg'`
Response: "Dashboards added", 200

- Delete dashboards:
`curl 192.168.3.74:3001/dashboards -X DELETE -d '{"deployment_label":"test-sec","monitoring_id":"as54d5a-trvb2yh58-dsada9s5fd8f"}' -H'Content-Type: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA...eQQ76mK9vDG9WmeJ44lbhDtbEDMzKsbA6QKvs6xFk2RRRL2VHF9iG21xSO5AIU-VcJEc7uQNZkwNwg'`
Response: "Dashboards deleted", 200

- Get dashboard URLS corresponding to a monitoring_id:
`curl 192.168.3.74:3001/dashboards/deployment/as54d5a-trvb2yh58-dsada9s5fd8f -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA...eQQ76mK9vDG9WmeJ44lbhDtbEDMzKsbA6QKvs6xFk2RRRL2VHF9iG21xSO5AIU-VcJEc7uQNZkwNwg'`
Response: 
```
{
     "node":"/d/tA-D4hznz/sodalite-node-exporters-test-sec",
     "pbs":"/d/4mxD42k7k/sodalite-pbs-exporters-test-sec",
     "slurm":"/d/slbv42knk/sodalite-slurm-exporters-test-sec"
}
```

- Get dashboard URLS corresponding to a user:
`curl 192.168.3.74:3001/dashboards/user -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA...eQQ76mK9vDG9WmeJ44lbhDtbEDMzKsbA6QKvs6xFk2RRRL2VHF9iG21xSO5AIU-VcJEc7uQNZkwNwg'`
Response: 
```
{
     "as54d5a-trvb2yh58-dsada9s5fd8f": {
         "node":"/d/tA-D4hznz/sodalite-node-exporters-test-sec",
         "pbs":"/d/4mxD42k7k/sodalite-pbs-exporters-test-sec",
         "slurm":"/d/slbv42knk/sodalite-slurm-exporters-test-sec"
     }
}
```

**Comment by jramosrivas** [comment]
The full url of the dashboards is recreated as follows:

`http://<grafana-address>:3000/<received-value>`

**Comment by jesus-gorronogoitia** [comment]
IDE integration implemented and partially tested: creation and retrieval. Deletion testing pending.

**Comment by jesus-gorronogoitia** [comment]
Dashboard deletion integrated in application undeployment
