### ISSUE TITLE
Validation cases for requirements

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#16]
We followed this [paper](https://www.researchgate.net/publication/326255293_Sommelier_A_Tool_for_Validating_TOSCA_Application_Topologies 
) for validating TOSCA requirements in the semantic reasoner.
In TOSCA, the source of a relationship is a requirement of a node.
Overall, we should validate, the sources, the relationships, and the target of a node.
In this issue, we ll discuss the validation of the sources of a node which are the requirements. 
In page 9 of the paper, there are the conditions for validating a requirement.
When IDE user sends /saveAADM, if reasoner locates that a requirement violates the constraints, an error is added to the errors section in the JSON response.

I raised this issue, so as to discuss the cases, and testing the integration of those validations cases with the IDE.

Error examples in yaml: 
[Requirements_examples_yaml.txt](https://github.com/SODALITE-EU/ide/files/4751717/Requirements_examples_yaml.txt)
Error response of saveAADM:
[Error_response_example.txt](https://github.com/SODALITE-EU/ide/files/4751721/Error_response_example.txt)

**Tier 2 and tier 1 in turtle containing the error examples in the yaml file above (Requirements_examples_yaml.txt):**
Tier 2 used for testing:
[snow_requirements.aadm.txt](https://github.com/SODALITE-EU/ide/files/4751754/snow_requirements.aadm.txt)
Tier 1 used for testing:
[requirements_tier_1.ttl.txt](https://github.com/SODALITE-EU/ide/files/4751725/requirements_tier_1.ttl.txt)

**Comment by zoevas** [comment]
Updated details about integration here: [url](https://docs.google.com/document/d/1zP4-6ifwiO7z6Q4XMCqVZncTPE-iHylpUAfjjSboc5Y/edit?usp=sharing)

**Comment by jesus-gorronogoitia** [comment]
Current semantic validation is supported in IDE
