### ISSUE TITLE
IDE configuration of back-end services through a config file

### ISSUE THREAD

**Issue by dradX** [SODALITE-EU/ide#17]
It would be useful to have the possibility to enable the IDE configuration of external SODALITE services, like REST API URI endpoints, through a configuration file. This would enable external tools to setup the complete deployment of the SODALITE Stack.

**Comment by jesus-gorronogoitia** [comment]
Storing Sodalite IDE backend preferences in workspace configuration following [the standard procedure](https://www.vogella.com/tutorials/EclipsePreferences/article.html)

**Comment by jesus-gorronogoitia** [comment]
Backend services endpoints are stored in this path relative to the user's workspace:
_.metadata/.plugins/org.eclipse.core.runtime/.settings/org.sodalite.dsl.preferences.prefs_
with this content:
```
IaCURI=http\://154.48.185.202\:8080/a
KBReasonerURI=http\://160.40.52.200\:8084/reasoner-api/v0.6/a
XOperaURI=http\://154.48.185.206\:5000/a
eclipse.preferences.version=1
```
Note that colon in URLs must be escaped. This approach is not compatible with a CI/CD file-based pre-configuration, so I will implement such a support.

**Comment by jesus-gorronogoitia** [comment]
A sodalite.properties file located at the root folder of the Eclipse installation is read by Eclipse upon launching to get default endpoints of the Sodalite Backend services. The sodalite.properties content is the following:
```
KBReasonerURI=http://160.40.52.200:8084/reasoner-api/v0.6/
IaCURI=http://154.48.185.202:8080/
XOperaURI=http://154.48.185.206:5000/
```
Note this pre-configuration is loaded as default by Eclipse in every launch, but it only applies in the first launch, while in the following the configuration set by the user in the preferences page prevail (the default one from this properties file in the user has not changed the configuration)

I will modify the build of the IDE Docker image to include this sodalite.preferences file. See #20

**Comment by jesus-gorronogoitia** [comment]
sodalite.properties is included in SODALITE IDE container with default backend configuration. File sodalite.properties locate in Docker/ directory can be edited before creating the Docker image.
Once the IDE starts the first time reads this default configuration. In following launches, the IDE always read the latest configuration set by the user, but the user can return to the default IDE backend configuration by clicking on restore defaults button, followed by apply changes button.

**Comment by jesus-gorronogoitia** [comment]
Note: In case users have chosen to use Oomph to manage default preferences, Oomph may return to defaults after each IDE launch. If this is not the desire behavior, go to top menu Navigate/Open setup/user are remove default values for Sodalite backend services

**Comment by jesus-gorronogoitia** [comment]
@dradX This feature is implemented and tested by myself. I will keep it in Review in progress state until it is tested by others

**Comment by jesus-gorronogoitia** [comment]
See #20 for an example of sodalite.properties with backend enpoints to be injected into the IDE container. The file needs to be available in the directory from where the IDE container is launched using the `start_sodalite_ide_container.sh` script.
