### ISSUE TITLE
Support for get_artifact function

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#189]
TOSCA specification provides [get_artifact function](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969460) in order to associate artifacts with the entities in the service template. To the certain extend, [implementation artifacts](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969466) (e.g. playbooks and configs) can be linked in the resource models via dependencies, however, it cannot be done for deployment artifacts (e.g. application tarballs) in the node templates in AADM.

# Expected behavior
xOpera-examples repository has [an example](https://github.com/xlab-si/xopera-examples/blob/master/tosca/artifacts/service.yaml) of usage of get_artifact function. The artifacts can be associated both in node_types and node_templates. As with the implementation artifacts, the deployment artifacts should be encoded and uploaded to the KB, and be retrieved and accessible in the backend services, such as IaC-Blueprint-Builder and Orchestrator.

**Comment by jesus-gorronogoitia** [comment]
Hi @kmlTE I will implement this feature as soon as we complete the bug fixing for semantic validation required by the EGI webinar. Hope this feature can wait.

**Comment by jesus-gorronogoitia** [comment]
Support for artifacts in RMs, AADMs, and get_artifact function implemented in https://github.com/SODALITE-EU/ide/commit/e6db23869310892c7a1036898006ee03d27cb64b

Please, update IDE and check
