### ISSUE TITLE
Add interface to upload JSON files to MODAK

### ISSUE THREAD

**Issue by dev-zero** [SODALITE-EU/ide#203]
The simplest integration with MODAK in the IDE is the possibility to upload JSON data to the endpoints:

- `/infrastructures`
- `/scripts`
- `/models`

When uploading, either a JWT token is needed (which is verified against the OpenID and needs the `modak_w` role) or a fixed API key (which is usually dynamically generated on each MODAK webapp server startup).

It would be great if the IDE would syntax-highlight/auto-complete/lint a JSON based on the JSON schema.

**Comment by dev-zero** [comment]
[modak-openapi.json.gz](https://github.com/SODALITE-EU/ide/files/7814217/modak-openapi.json.gz)
... I can also provide individual JSON schemas per endpoint.

**Comment by jesus-gorronogoitia** [comment]
Hi  @dev-zero Could you please much further elaborate this feature?:
- Who (user role) and when/where (IDE process) will upload the JSON? That is, it is not clear at all to me in which situation the user will want to upload the JSON file to MODAK? When editing an optimization model in the IDE editor, when deploying an AADM, elsewhere (at any time)?
- Why are there three possible MODAK endpoints? Who should select which endpoint to send the JSON to? How the user can select one of those? What is the information the user requires to take such decision?
- Please, provide the complete MODAK endpoint in private test bed and details about how to build the REST request: POST? payload, headers, etc. How JWT token is passed (as header authentication)? Please, provide a curl example to invoke your API.
- The IDE is an Eclipse plugin. Therefore, users can install any of those JSON editors available in Eclipse for JSON syntax highlighting, content assistance and syntactic validation.

**Comment by dev-zero** [comment]
> Hi @dev-zero Could you please much further elaborate this feature?:
> 
>     * Who (user role) and when/where (IDE process) will upload the JSON? That is, it is not clear at all to me in which situation the user will want to upload the JSON file to MODAK? When editing an optimization model in the IDE editor, when deploying an AADM, elsewhere (at any time)?

I guess this would be the quality expert again. MODAK execution is a 2 step process:

1. the QE registers an image together with some metadata with MODAK
2. MODAK is queried to get a container plus job scripts when an app should be deployed

Now (and this is this new integration) we also store information about the infrastructure (configuration of a cluster) as well as configuration snippets ("scripts") required to run an app in MODAK, plus optionally a scaling model for an application.
This happens most likely as part of the first step, and likely by the same person/role. An infrastructure can be referenced by either a script (as a condition when to be enabled) or an application scaling model.

>     * Why are there three possible MODAK endpoints? Who should select which endpoint to send the JSON to? How the user can select one of those? What is the information the user requires to take such decision?

We have multiple independent pieces: infrastructure configuration information, script (snippets) to run an app on an infra, an optional scaling model. Hence 3 resource URLs. The configuration in the IDE should not require the spec of all 3 endpoints, just the main MODAK URL, plus maybe allow to specify the API key as an alternative to using the request from keycloak.

>     * Please, provide the complete MODAK endpoint in private test bed and details about how to build the REST request: POST? payload, headers, etc. How JWT token is passed (as header authentication)? Please, provide a curl example to invoke your API.

Ok, will do. The request is properly REST structured: POST for creating a resource, GET to either get a list or a single resource given an ID. JSON is sent in the body. JWT token is to be passed in the header. Ex.:

```
curl -X 'POST' \
  'http://localhost:5000/infrastructures' -H 'Authorization: Bearer 43eaebd2b1e24a749ef0e1c31d8efe0f' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "string",
  "disabled": "2021-12-09T14:51:34.213Z",
  "description": "string",
  "configuration": {
    "scheduler": "slurm",
    "storage": {
      "file:///scratch": {
        "storage_class": "default-high"
      },
      "file:///data": {
        "storage_class": "common"
      }
    },
    "partitions": {
      "mc": {
        "nnodes": 100,
        "node": {
          "ncpus": 2,
          "cpu": {
            "arch": "x86_64",
            "microarch": "zen2",
            "ncores": 64,
            "nthreads": 2
          },
          "naccel": 0,
          "memory": "512GiB"
        }
      },
      "gpu": {
        "nnodes": 5,
        "node": {
          "ncpus": 1,
          "cpu": {
            "arch": "x86_64",
            "microarch": "zen2",
            "ncores": 32,
            "nthreads": 2
          },
          "naccel": 2,
          "accel": {
            "type": "gpu",
            "model": "P100"
          },
          "memory": "256GiB"
        }
      }
    }
  }
}'
```

HTTP error codes should be properly mapped (201 when successfully created, 401 missing/invalid auth, 409 on constraint failure, 400 on invalid json).

**Comment by jesus-gorronogoitia** [comment]
Implement IDE top-menu and json-file selected contextual menu "Manage MODAK definitions" to send the file to MODAK endpoint. The menu entry triggers a wizard that offers the user to select the kind of definition: infrastructure, script, scaling model. The wizard also offers the user to select a JSON model (only if triggered from top-menu). In this case, if not selected, the JSON model opened in active editor is used.

**Comment by jesus-gorronogoitia** [comment]
Feature implemented. Testing pending of MODAK availability in private testbed.
Feature is accessible through top-menu:
![modak1](https://user-images.githubusercontent.com/3658315/148782240-8a4e3b05-9ca2-47f2-b60a-f13c7093248e.png)

or from contextual menu for selected definition file:
![Modak2](https://user-images.githubusercontent.com/3658315/148782529-a705adfc-e7e5-4e41-834a-acec29c1dee7.png)

Both triggers a wizard, but in the second case the definitions file is pre-set:
![modak3](https://user-images.githubusercontent.com/3658315/148782888-3712aef3-d1cc-415a-ba47-111e17f5feb9.png)
![image](https://user-images.githubusercontent.com/3658315/148782999-558f55bd-74e1-416c-9347-431d1beb54df.png)
When accepted, if the definition file was not set (first case above), the IDE looks for a JSON model opened in front editor (current selected editor). If so, it asks the user for confirmation to use that definition model. If accepted, it requests MODAK to manage this definition model. If denied, it cancels.
![image](https://user-images.githubusercontent.com/3658315/148783608-da0a70e3-b8cd-43c7-9dcc-ac08cb5adfcf.png)

If opened model in front editor, it reports a error and cancels.
![image](https://user-images.githubusercontent.com/3658315/148783811-a831052e-ec68-4afc-adcf-874428ff6db1.png)
