### ISSUE TITLE
support "import" directive

### ISSUE THREAD

**Issue by gmeditsk** [SODALITE-EU/ide#23]
Based on my understanding, we need to allow users in the IDE to split their models in multiple files and use import statements. Then, we need to update the interaction between the IDE and the Reasoner APIs (i.e. the exchange model + the API parameters, if needed).

Here are the links of the examples that Dragan sent:

> As discussed before Alexander prepared a refined version of SnowUC blueprint here:
> https://github.com/SODALITE-EU/iac-management/tree/master/use-cases/snow-uc/snow-demo
>
>and
>
> Vehicle IoT Uc here:
> 
> https://github.com/SODALITE-EU/iac-management/tree/master/use-cases/vehicleiot-uc/full-demo
> 
> Using comon node definition as modules here:
> 
> https://github.com/SODALITE-EU/iac-management/tree/master/use-cases/modules
> 

Clinical UC:
https://github.com/SODALITE-EU/iac-management/tree/master/use-cases/clinical-uc/hpc-clinical-uc

**Comment by jesus-gorronogoitia** [comment]
Please, provide a very detailed description of this new feature. Otherwise, I cannot implement it

**Comment by dradX** [comment]
**Description**
The user should have the possibility to _group_ selected node definitions within the IDE to make them reusable within the same _workspace_ (private) or to all active workspaces (public) in the Knowledge Base (KB) - creating _modules_. 
The user can then select which of the modules he intends to reuse from the list of _public modules_ and _private modules_ in order to setup the scope for code reuse and KB searches. 
It would be helpful if this _module tag_ would be something like a path or simple URI the user can simply remember. 
This information should be stored with the node definition and used in the AADM JSON export definition so that the user can 
In TOSCA this is done with the import directive - examples above.

**Comment by jesus-gorronogoitia** [comment]
I've created AADM and RM models for snow use case and all the imports included. Imported models are modeled as RM instances. It is pending to push these RM model and AADM models into the KB, but before, I want to discuss some implications with @zoevas

**Comment by jesus-gorronogoitia** [comment]
> **Description**
> The user should have the possibility to _group_ selected node definitions within the IDE to make them reusable within the same _workspace_ (private) or to all active workspaces (public) in the Knowledge Base (KB) - creating _modules_.
> The user can then select which of the modules he intends to reuse from the list of _public modules_ and _private modules_ in order to setup the scope for code reuse and KB searches.
> It would be helpful if this _module tag_ would be something like a path or simple URI the user can simply remember.
> This information should be stored with the node definition and used in the AADM JSON export definition so that the user can
> In TOSCA this is done with the import directive - examples above.

This feature is already supported by the KB, as already discussed offline in a conference call. All resources defined within a RM as already available in the KB to be reused by another AADM. The implementation of public/private workspaces in the KB is a feature to be requested in another issue in the Semantic Reasoner repository.
The  module keyword can be implemented into the RM as an alias for the RM URI provided by the KB, but it also requires support in the KB schema. When the module keyword is used in the AADM, as a sort of import, it will constraint the types to be used from the KB to those declared within that module tag in the corresponding RM. I add @zoevas as assignee to take care of the KB implementation.

**Comment by jesus-gorronogoitia** [comment]
Created RM and AADM models for Vehicle IoT

**Comment by jesus-gorronogoitia** [comment]
Module RMs (Docker, OpenStack), Snow RMs and AADM saved into the KB.

**Comment by jesus-gorronogoitia** [comment]
@dradX This is the KB generated Json for the Snow AADM corresponding to the Snow Tosca YAML in the issue description

[snow_v2.zip](https://github.com/SODALITE-EU/ide/files/4917898/snow_v2.zip)

**Comment by jesus-gorronogoitia** [comment]
@dradX I need the certificates that are required for the types defined in the module docker-certificate.yaml so I can populate the KB with these types. Thanks

**Comment by jesus-gorronogoitia** [comment]
Task: create RMs and AADMs for Clinical UC

**Comment by jesus-gorronogoitia** [comment]
Done: create RMs and AADMs for Clinical UC. Detected a circular dependency between RMs that need to be fixed. Resoure Models (modules) for torque and datamover cannot be yet pushed into the KB. Output_hpc and image puller RMs have been pushed into the KB

**Comment by jesus-gorronogoitia** [comment]
Instructions to open an IDE with latest UC models and push models into the KB
(Instructions given for a computer with Linux OS. If you are using Windows, contact @alexmaslenn for support)

1- Pull master branch of IDE repository
`git clone https://github.com/SODALITE-EU/ide.git`
2- Go to ide/Docker directory
3a- Launch the IDE by running the script `start_sodalite_ide_container.sh`. 
3b- if the _sodalite-ide:latest_ cannot be retrieved from the DockerHub or the project _org.sodalite.dsl.examples_ available in the workspace of the IDE does not contain the latest UC models, generate the _sodalite-ide:latest_ by running the script `create_sodalite_ide_image.sh`; next, try 3a again.
4- In the IDE, in the project explorer view, expand the _org.sodalite.dsl.examples_ project. In the folder modules, you will find RMs for modules required by the UCs. They need to be pushed into the KB before pushing any UC model. 
4a- Clinical UC: the clinical folder contains the AADM of this UC
4b- Snow UC: Snow.v2 folder contains the AADM modes of this UC. snow_resources.aadm must be pushed into the KB before pushing the snow_app.aadm.
4c- VehicleIoT UC: vehicleiot folder contains the AADM modes of this UC. vehicleiot_resources.aadm must be pushed into the KB before pushing the vehicleiot_app.aadm.
5- Save RMs into the KB: right click on the RM you want to save into the KB, and select the menu entry _Sodalite/Save RM into the KB_. Upon completion, you will be notified with a dialog (similarly in case of error)
6- Save AADM into the KB: right click on the AADM you want to save into the KB, and select the menu entry _Sodalite/Save AADM into the KB_. Upon completion, you will be notified with a dialog (similarly in case of error)

**Comment by zoevas** [comment]
> Done: create RMs and AADMs for Clinical UC. Detected a circular dependency between RMs that need to be fixed. Resoure Models (modules) for torque and datamover cannot be yet pushed into the KB. Output_hpc and image puller RMs have been pushed into the KB

Regarding the two resource models that cannot be saved to the KB, error is thrown because a node type does not exist:
**1) data_mover.rm.ttl**
[data_mover.rm.ttl.txt](https://github.com/SODALITE-EU/ide/files/4982254/data_mover.rm.ttl.txt)
sodalite.data.mover node type does not exist in KB
**2) torque.rm.ttl**
[torque.rm.ttl.txt](https://github.com/SODALITE-EU/ide/files/4982252/torque.rm.ttl.txt)
sodalite.nodes.hpc.job.torque.configuration node type does not exist in KB

**Comment by jesus-gorronogoitia** [comment]
> > Done: create RMs and AADMs for Clinical UC. Detected a circular dependency between RMs that need to be fixed. Resoure Models (modules) for torque and datamover cannot be yet pushed into the KB. Output_hpc and image puller RMs have been pushed into the KB
> 
> Regarding the two resource models that cannot be saved to the KB, error is thrown because a node type does not exist:
> **1) data_mover.rm.ttl**
> [data_mover.rm.ttl.txt](https://github.com/SODALITE-EU/ide/files/4982254/data_mover.rm.ttl.txt)
> sodalite.data.mover node type does not exist in KB
> **2) torque.rm.ttl**
> [torque.rm.ttl.txt](https://github.com/SODALITE-EU/ide/files/4982252/torque.rm.ttl.txt)
> sodalite.nodes.hpc.job.torque.configuration node type does not exist in KB



Yes, both types are defined within those Turtle serializations you attached. _sodalite.data.mover_ is indeed defined in **data_mover.rm.ttl** and _sodalite.nodes.hpc.job.torque.configuration_ in **torque.rm.tll**.  So, I assume the there must be another hidden reason. Please @zoevas  have a look when you come back

**Comment by jesus-gorronogoitia** [comment]
data_mover.rm and torque.rm have been split so that the referenced definitions are included in data_mover_defs.rm and torque_defs.rm, as suggested by @zoevas. However, I am still getting an 500 Internal Server Error when these models are pushed into the KB, excepting for the data_mover_defs.rm. I need to wait for @zoevas to get information about these errors

**Comment by jesus-gorronogoitia** [comment]
**TODO**: Create AADM/RMs for [MODAK models](https://github.com/SODALITE-EU/iac-management/tree/master/hpc/modak)

**Comment by jesus-gorronogoitia** [comment]
DONE: MODAK models (RM, AADM) create. Only data types RM could be stored into the KB. The other two: job RM and modak AADM could not be stored. Job RM could not be stored because it references other types declared within it, and this is not yet supported by the current KB reasoner. AADM could not be stored because the job RM definitions where not available in the KB

**Comment by jesus-gorronogoitia** [comment]
All UCs models (RMs, AADMs) created in the IDE and pushed into the KB

**Comment by gmeditsk** [comment]
Nice! Therefore the integration tests can continue now. Thanks @jesus-gorronogoitia and @zoevas !

**Comment by jesus-gorronogoitia** [comment]
This feature should be reformulated.
There is not need of an import statement as the classic import that injects other model definitions, as they are all available from the KB. The import statement here is providing a namespace of KB entities to be reused in this model when using content-assistance, so only the resources defined within that namespace are returned.
For that, the KB should provide a list of available namespaces for imports

**Comment by jesus-gorronogoitia** [comment]
Implemented grammar support in AADM and RM for directives:
namespace: [label] # associates a namespace label to the entities defined within this aadm
import: [label] #multiple sentences permitted.

**Comment by jesus-gorronogoitia** [comment]
Module and import directives supported in AADM and RMs. Implementation committed in https://github.com/SODALITE-EU/ide/commit/6908ebc6c3be8b83aeb6e6df3706769f930ee58c
