### ISSUE TITLE
Escaping strings

### ISSUE THREAD

**Issue by gmeditsk** [SODALITE-EU/ide#34]
For textual (free text) values, like node descriptions, we need to escape the strings. For example, the following throw errors:

- exchange:description ' The container's hostname is "fake" ' ;
- exchange:description " The container's hostname is "fake" " ;

It should be:
- exchange:description 'The container\\'s hostname is "fake" ' ;
- exchange:description "The container's hostname is \\"fake\\"" ;

Normally, if we use existing libraries for JSON and RDF serialisation/deserialisation, escaping is automatically handled. From an RDF point of view, strings should be enclosed in double quotes, even if it also works with single quotes.

I am raising this issue because I accidentally found the following definition in the [docker_component.rm.ttl](https://drive.google.com/file/d/17yqO-UgzdsfaMIm6elx4DBIuBmZqs_s5/view?usp=sharing), which is wrong:

```
:Property_9 
  rdf:type exchange:Property ;
  exchange:name "hostname" ;
  exchange:description 'The container's hostname' ;
  exchange:hasParameter :Parameter_120 ;
  exchange:hasParameter :Parameter_121 ;
```
I am not sure if this affects the mapping of our examples, but we need to check this and fix it, if needed.

**Comment by jesus-gorronogoitia** [comment]
Solved. Single quotes in comments are escaped in Turtle serialization for both AADM and RMs.
