### ISSUE TITLE
Fixing errors in the exchange ttl models (issues located by testing the aadm json in KB server)

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#35]
Have in mind, that we made some manual changes to the KB for those models.
However, those models cannot be used for demo, as the resource and app instances have been saved seperately,
and we want them in one model (refer to 5 bullet).

For getting a correct aadm json, I saved those aadm models containing both resource and app instances in one aadm:
1) snow
[snow_aadm_manual.ttl.txt](https://github.com/SODALITE-EU/ide/files/5006845/snow_aadm_manual.ttl.txt)
AADM URI: https://www.sodalite.eu/ontologies/workspace/1/ncg752264i33rm8pfkd6mhb6ho/AADM_m7j1okimgfkgrihq41khqk7ofi
2) vehicle
[vehicleiot_aadm_manual.ttl.txt](https://github.com/SODALITE-EU/ide/files/5006849/vehicleiot_aadm_manual.ttl.txt)
AADM URI:
https://www.sodalite.eu/ontologies/workspace/1/kuo5nrsil2t33ktj3mb8sfnci2/AADM_bq0et55911jv2rcsr07v7j2jth
3) An aadm having optimization
[optimization_aadm_manual.ttl.txt](https://github.com/SODALITE-EU/ide/files/5006848/optimization_aadm_manual.ttl.txt)
AADM URI:
https://www.sodalite.eu/ontologies/workspace/1/cem2u0h71q2odl4fm8o6k69g5k/AADM_me7sho52bqqi2qmc2q5vnauvdq

But, for not creating models in ttl format manually, the following actions should be made so as to resave the models for producing a correct aadm json:

### 1) Change the name of  sodalite.nodes.OpenStack.SecurityRule - Action required

The name of sodalite.nodes.OpenStack.SecurityRule data type should be 
sodalite.datatypes.OpenStack.SecurityRule  according to [https://github.com/SODALITE-EU/iac-management/blob/master/use-cases/modules/openstack/openstack_security_rule.yaml#L5](yaml)
The resource model is this:
https://www.sodalite.eu/ontologies/workspace/1/i33oic0aohevnjrr7gibsjt5cv/RM_b6pm5qpedsv3albf93nlfbufko

### 2) Wrong value for entry schema in sodalite.nodes.OpenStack.SecurityRules resource model - Action required
This 
The exchange format of _sodalite.nodes.OpenStack.SecurityRule_ node does not contain the correct value ('org.sodalite.dsl.rM.impl.EDataTypeImpl@178283af ). We see the correct one in [yaml](https://github.com/SODALITE-EU/iac-management/blob/ebe446068c4c11e0e271d242100e3c25239ec293/use-cases/modules/openstack/openstack_security_rule.yaml#L39). So the wrong value has been saved in the KB for this node type:

Right now, I changed the https://www.sodalite.eu/ontologies/workspace/1/i33oic0aohevnjrr7gibsjt5cv/RM_b6pm5qpedsv3albf93nlfbufko  resource model, so as to have the correct value for the entry_schema.

**For the serialization of dsl to turtle:**
Instead of this parameter, 
```
:Parameter_50
  rdf:type exchange:Parameter ;
  exchange:name "entry_schema" ;
  exchange:value 'org.sodalite.dsl.rM.impl.EDataTypeImpl@178283af (name: sodalite.nodes.OpenStack.SecurityRule)' ; 
.
```

**The resource model should have it as:**
```
:Parameter_50
  rdf:type exchange:Parameter ;
  exchange:name "entry_schema" ;
  exchange:hasParameter :Parameter_40
.

:Parameter_60
  rdf:type exchange:Parameter ;
  exchange:name "type" ;
  exchange:value 'sodalite.datatypes.OpenStack.SecurityRule' ;    <---- this datatype exist after the change in bullet 1
.
```

Whole model here: [openstact_security_rule_MODIFIED.rm.ttl.txt](https://github.com/SODALITE-EU/ide/files/4996086/openstact_security_rule_zoe_MODIFIED.rm.ttl.txt)
### 3) security-rules-snow template: group_name and group_description
According to [yaml](https://github.com/SODALITE-EU/iac-management/blob/691d2934fb6e20df656db51acb77c763bd66c493/use-cases/snow-uc/snow-demo/service.yaml#L74), group_name, group_description should be properties and NOT parameters under ports property.

We applied this change manually for the security-rules-snow template for https://www.sodalite.eu/ontologies/workspace/1/5nq8pufmcm9ia090hd9rjghaj7/AADM_t2b6son1rf8ml0jpse7s4m28r8 aadm.

Exchange ttl model for this template should have group_name and group_description as properties, so as next time this aadm is saved to be correct.

### 4) Two templates with the same name cannot exist in KB 
Remove any template that have the same name with other one, make sure that there is no reference to it.
security-rules-snow was present twice. The following template was removed from https://www.sodalite.eu/ontologies/workspace/1/esbfi1jd99uovqjeusvne60vlt/AADM_8ej7qtdujoh365aejq064k7vt0 aadm
It was referenced nowhere.
https://www.sodalite.eu/ontologies/workspace/1/esbfi1jd99uovqjeusvne60vlt/security-rules-snow

### 5) Return to the previous approach by having both resource and app instances in the same aadm. 
The seperation of resource and app instances in different aadms cannot be supported right now, as all those instances should be returned in the same aadm json and right now this cannot be done with the current implementation in reasoner.

**Comment by jesus-gorronogoitia** [comment]
Issues fixed:
1- Fixed in openstack_security_rule.rm. Model not pushed into the KB.
2- Turtle serialization fixed.
3- Fixed in AADM models. Models not pushed into the KB.
4- N/A Current pushed AADM models do not correspond to the identified one. KB should reject to push a node template that already exist into the KB within the same AADM. I will create a KB issue.
5- I've created a complete Snow AADM model that includes all templates for review demo. Model not pushed into the KB. I will do it as soon as you give me green light.
