### ISSUE TITLE
Escaping playbook content

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#36]
For example in DockerHost turtle resource model has as content for create_docker_host.yaml
line: "{\"mtu\": 1450}"
\ should be retained 
[Like here](https://github.com/SODALITE-EU/iac-management/blob/5ac632249ef46af57b1a7a20b605845eb514d439/use-cases/modules/docker/playbooks/create_docker_host.yml#L21  )

However, if you save this in KB, this is saved as line: "{"mtu": 1450}", since \ escapes ".

This is how it was sent to KB through the exchange ttl model:
```
:Parameter_1
  rdf:type exchange:Parameter ;
  exchange:name "path" ;
  exchange:value '/home/yosu/Projects/Sodalite/Git/iac-management/use-cases/modules/docker/playbooks/create_docker_host.yml' ;
.

:Parameter_2
  rdf:type exchange:Parameter ;
  exchange:name "content" ;
  exchange:value '---\n- hosts: all\n  become_user: root\n  become: yes\n  \n  vars:\n    pip_install_packages:\n      - name: docker\n    docker_package: "docker-ce-19.03.5-3.el7"\n  pre_tasks:\n  - name: update cache\n    package:\n      update_cache: yes  \n  tasks:\n  - name: Configure the docker mtu for OpenStack and restart docker host\n    block:\n      - lineinfile:\n          path: /etc/docker/daemon.json\n          line: "{\"mtu\": 1450}"\n          create: yes\n      - service:\n          name: docker\n          state: restarted\n  roles:\n    - role: geerlingguy.repo-epel\n      when: ansible_distribution == "CentOS"\n    - role: geerlingguy.pip\n    - role: geerlingguy.docker' ;
.
```

I changed it manually in the KB by sending {\\"mtu\\": 1450} so as to be saved as {\"mtu\": 1450}, but we should fix it so as the playbook to be saved correctly next time.

1) One solution could be to sent it as  line: "{\\"mtu\\": 1450}", by adding two slashes.
2) One other solution is to encode the strings like here:
https://meyerweb.com/eric/tools/dencoder/
so as not to face other issues with the special chars in the future.
We discuss which approach is the best. This issue requires collaboration between ide and reasoner.

**Comment by jesus-gorronogoitia** [comment]
Implemented solution 1, so that the serialized script contains substring `"{\\"mtu\\": 1450}". Pending of validations by storing RM into the KB when @zoevas gets available`
