### ISSUE TITLE
Saving AADM from project root folder returns an error

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#57]
### Prerequisites

1. SODALITE IDE is installed as Docker image
2. KB URI is configured properly

### Current behaviour

1. Create a project
2. Add AADM to the project root folder
3. Select Sodalite -> Save AADM to KB

IDE returns an error **String index out of range: -1**

If AADM file is moved to folder inside project folder this error does not appear.

### Expected behaviour
AADM is saved into KB without an error

**Comment by jesus-gorronogoitia** [comment]
Please, send me the AADM model that produced the error.

**Comment by alexmaslenn** [comment]
> Please, send me the AADM model that produced the error.

This happens with any AADM e.g the default one
```
node_templates:
	my_node:
		type: my.type

```

**Comment by jesus-gorronogoitia** [comment]
Fix in https://github.com/SODALITE-EU/ide/commit/916d0df36f97bf5a340b1166cdac73e6514bec94
