### ISSUE TITLE
Unable to copy blueprint id from Eclipse dialog box

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#59]
When blueprint is deployed (whether successfully or not) a blueprint ID is shown to the user in the dialog box. In some scenarios it could be useful to copy paste this ID.

### Current behaviour
User cannot copy to clipboard any information from dialog box. 

### Expected behaviour
User can copy information from dialog box.

**Comment by jesus-gorronogoitia** [comment]
I've implemented that when the dialog pops up the message reference (blueprint or model URL) is copied in the Clipboard so that it can be pasted in another place. I will create as well an entry in the error/warning views.
I will document this behavior in the tutorial

**Comment by jesus-gorronogoitia** [comment]
Messages reported by the IDE during its interaction with the backend services reported in Eclipse logging system (Error View).
Tutorial updated.
Fixed in https://github.com/SODALITE-EU/ide/commit/b402ac0fb69ff1f01f54df11b6fb9d0e0661a647
