### ISSUE TITLE
RM playbooks are not updated until any changes made to RM

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#60]
### Prerequisites

1. SODALITE IDE is installed as Docker image
2. KB URI is configured properly

### Current behaviour
1. Project is created and a RM with playbooks is included in the project.
2. Select RM ad select Sodalite -> Save RM to KB
3. Make some changes in playbook
4. Select Sodalite -> Save RM to KB

Playbooks in KB remain the same.
Related **.ttl** file located in **src-gen** does not change either.
In order to apply playbook changes, user needs to make any changes in RM, then playbook changes are applied also.

### Expected behaviour
Playbooks in KB are updated if user saves RM to KB.

**Comment by jesus-gorronogoitia** [comment]
I assume you have save locally the RM (in the workspace) before requesting to save the model into the KB, haven't you?

**Comment by alexmaslenn** [comment]
I did of course. That's is the issue. If there are no changes in RM but only in playbook, **Save Changes** trigger does not work, I suppose.

**Comment by jesus-gorronogoitia** [comment]
I see, the problem is that you have not change the RM, so the RM serializer is not invoked and the TTL file keeps unchanged. I will investigate the way to invoke the serializer upon saving into the KB

**Comment by jesus-gorronogoitia** [comment]
Fix in https://github.com/SODALITE-EU/ide/commit/d8e165223e5125b910e7c2f929c2068abd6ba8ae
Models are serialized in Turtle when users are requesting the model to be saved into the KB. Besides, when user tries to push into the KB an unsaved (locally) model, she is prompted to save it.
