### ISSUE TITLE
RMs with same filenames overwrite each other

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#61]
In case project contains several RMs with same filenames saving changes in any of them overwrites single **.ttl** file all these RMs are related to. The result of saving RM into KB becomes unpredictable. 

### Prerequisites

1. SODALITE IDE is installed as Docker image
2. KB URI is configured properly

### Current behaviour

1. Create a project
2. Create 2 folders in project (e.g **test1** and **test2**)
3. In each folder create an RM with same names (e.g **test1/test.rm** and **test2/test.rm**)
4. Modify and Save RM in **test1**
5. Check **src-gen/test.rm.ttl** file
6. Modify and Save RM in **test2**
7. Check that **src-gen/test.rm.ttl** file has changed

### Expected behaviour
TTL filename takes into account the folder RM is contained in.

**Comment by alexmaslenn** [comment]
Well I'm writing down all the issues I've encountered during test deployment. I do not expect them to be fixed instantly, just do not want them to be lost. This particular one gave me a hard time, until I realised the mechanics behind RM saving.

**Comment by jesus-gorronogoitia** [comment]
Fix in commit https://github.com/SODALITE-EU/ide/commit/3300cde80a82e4faa6fa9bb35632751f64575b76
