### ISSUE TITLE
Replacing tabs with spaces leads to unclear error in RM

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#66]
### Current behaviour

1. Take a valid RM file
2. Remove one indentation tab
3. Replace it with spaces
4. The model looks like valid but there is an unclear error `mismatched input '' expecting RULE_END`

### Expected behaviour
IDE shroud either provide a meaningful error or allow mixing spaces and tabs

**Comment by jesus-gorronogoitia** [comment]
SODALITE languages are positional (based on indentation) requiring tabs. Spaces are not supported. 
Reported errors are provided by Xtext, and I have no idea if providing better hints would be possible, but I will investigate. The best solution will come when automatic layout formatting will be implemented
