### ISSUE TITLE
KB/IDE User's management

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/ide#8]
KB/IDE should support the assignment of AADMs/RMs to concrete users, and therefore, they should support some short of simplified user's management.
- KB: support CRUD operations on user's
- IDE: view to support single user's management: CRUD

We could consider the need of supporting teams and roles.
As much as possible we should leverage state of practice frameworks for user's management

**Comment by gmeditsk** [comment]
I would suggest for this feature to rely on existing frameworks (third-party framework/tool) for user management, in order not to reinvent the will and implement from scratch a user management framework, meaning that credentials may need to be outside the KB.

**Comment by jesus-gorronogoitia** [comment]
Feature supported in IDE (Keycloak user management) and IDE-Backend interactions
