### ISSUE TITLE
AADM Json issues for snow use case

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#89]
As @salonikyal reported in the deployment pipeline channel, there are some issues in the aadm json for the snow use case.
I am creating this issue so as not to forget that.
### **1) req_cap** 
It is either as a string or array. I should be in one format.
```
"req_cap": [
                "network"
              ]
```
or
`"req_cap": "snow/sodalite.nodes.ConfigurationDemo.remote_server`

I see that req_cap in snow aadm is passed as listValue, so in aadm json is depicted as array, while in e..g DockerizedComponent is as string, because the values in exchange format is assigned as exchange:value

As a list:
```
"https://www.sodalite.eu/ontologies/workspace/1/global/snow-webcam-crawler": {
    "type": "https://www.sodalite.eu/ontologies/workspace/1/docker/sodalite.nodes.DockerizedComponent",
    "isNodeTemplate": true,
    "properties": [
       .....
        "https://www.sodalite.eu/ontologies/workspace/1/docker/docker_network_name": {
 "req_cap": [
                "tosca.nodes.Container.Application.network"
              ]
```

```
:Parameter_19
  rdf:type exchange:Parameter ;
  exchange:name "req_cap" ;  
  exchange:listValue "tosca.nodes.Container.Application.network" ; 
.
```

And in type as a value:
```
  "https://www.sodalite.eu/ontologies/workspace/1/docker/sodalite.nodes.DockerizedComponent": {
      "public_address": {
                    "default": {
                      "get_attribute": {
                        "attribute": "public_address",
                        "req_cap": "docker/sodalite.nodes.DockerHost.host",
                        "entity": "SELF"
                      }
                    }
                  },
```

```
:Parameter_52
  rdf:type exchange:Parameter ;
  exchange:name "req_cap" ;  
  exchange:value 'docker/sodalites.nodes.DockerHost.host' ; 
.
```
**QUESTION: Maybe as a string in the node type is correct? because in the node type definition, we denote the req_cap type?
I do not know what this req_cap is.**
### **2) valid_source_types** 
 Sometimes valid_source_types is a list, sometimes is a dictionary, and it should not be present when its empty
 If you notice  sodalite.nodes.OpenStack.VM capability, in the exchange format, it is sent as empty to the reasoner. It should have a value, otherwise it should not be sent:
```
:Parameter_112
  rdf:type exchange:Parameter ;
  exchange:name "valid_source_types" ;
.
```

### **3) sodalite.datatypes.OpenStack.SecurityRule**
The type is wrongly sent from ide.
**Actual**
```
"entry_schema": {
              "type": "org.sodalite.dsl.rM.impl.EPREFIX_TYPEImpl@49147941 (type: sodalite.datatypes.OpenStack.SecurityRule) (module: openstack)"
            }
```

**Expected**
  ```
          "entry_schema": {
              "type": "sodalite.datatypes.OpenStack.SecurityRule"
            }
```

### **4) inputs**
I am not sure I understand the issue here. Instead of _snow/sodalite.nodes.ConfigurationDemo.remote_server_, it should be remote_server? This issue was reported by Alexander. First, for being sure, we should ask him before fixing it.

```
inputs:
              mysql_db_pass: {default: {get_property: [SELF, mysql_db_pass]}}
              remote_server: {default: {get_attribute: [SELF, snow/sodalite.nodes.ConfigurationDemo.remote_server,
                    public_address]}}
```
should be
```
 inputs:
              mysql_db_pass: {default: {get_property: [SELF, mysql_db_pass]}}
              remote_server: {default: {get_attribute: [SELF, remote_server, public_address]}}
```
### **5) get_input should be passed as an object like get_property and not a string.**
```
  {
        "https://www.sodalite.eu/ontologies/workspace/1/docker/env": {
          "value": "{ get_input: mysql-env }",
          "label": "env"
        }
      }

```
Expected
```
"properties": [
      {
        "https://www.sodalite.eu/ontologies/workspace/1/docker/env": {
          "specification": {
            "get_input": "mysql-env"
          }
        }
      }
    ],
```

e.g. in _snow-my-sql_ template, the get_input is passed as a value. If you pass it as parameters, _get_input_ will be returned as a json object.
Not like this:
```
 :Property_38
  rdf:type exchange:Property ;
  exchange:name "env" ;
  exchange:value "{ get_input: mysql-env }" ;
.
```
But through parameters:
```
:Property_38
  rdf:type exchange:Property ;
  exchange:name "env" ;
  exchange:hasParameter :Parameter_1 ;

:Parameter_1
  rdf:type exchange:Parameter ;
  exchange:name "get_input" ;
  exchange:hasValue "mysql-env";
```

**Comment by jesus-gorronogoitia** [comment]
Please @zoevas For each point, provide a description how the AADM/RM should be serialized in Turtle, so your KB Reasoner translator produces the expected JSON
Please @salonikyal tell me what are the AADMs (Snow, Vehicle, Clinical) for which you are facing these problems
Thanks you both

**Comment by zoevas** [comment]
1. About **point 1** I have a doubt if req_cap should be as a string or as a list. The requirement by Saloni is that it should be in one format, either as a string or as list. Just I have a doubt about why it is currently as a list in templates. Maybe more than one value is needed for req_cap in node template?
For **4. point**, it is not a serialized problem, just a change with one value. 

For the other points, serialization instructions are given.

**Comment by jesus-gorronogoitia** [comment]
Issues fixed exception number 4, which requires further clarifications. @alexmaslenn contacted by Slack to request him further information about issue 4

**Comment by salonikyal** [comment]
@jesus-gorronogoitia  Hello, Sorry for the late response, unfortunately I didnot receive any notification or I might have skipped it.  I was facing issues with the snow use case. Thanks for fixing the issues.

**Comment by jesus-gorronogoitia** [comment]
Closing as AADM deployment works
