### ISSUE TITLE
Errors in Optimization DSL

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#90]
The optimization model should allow empty values (e.g. acc_type can be either empty string or skipped completely), as well as skip some values that are unused (e.g. data keyword is not used for mpi).

Another issue is that only "mvapch" and "opnmpi" are suggested, but mpich library is absent, and optimization model should include it. Also, it can be observed that openmpi library is misspelled ("opnmpi" is suggested).

![Screenshot from 2021-01-26 15-14-17](https://user-images.githubusercontent.com/2138519/106886031-b712bd00-66e3-11eb-8466-ad0a801141d9.png)

**Comment by jesus-gorronogoitia** [comment]
Hi  @kmlTE 
I've fixed these issues, as shown below
![image](https://user-images.githubusercontent.com/3658315/107210192-18000500-6a04-11eb-8b2a-b091a2686ac2.png)
However, for acc_type I can't set an empty value, so I've opted for "none". If this is not acceptable, please, inform me about another label for the default or unset value.
If you are fine, please, close this issue
Changes posted to master branch

**Comment by kmlTE** [comment]
@jesus-gorronogoitia Thank you!
