### ISSUE TITLE
Enable the user to start image-building process from IDE

### ISSUE THREAD

**Issue by dradX** [SODALITE-EU/ide#93]
The user is able to start and execute the image building process by choosing the JSON image builder config ([examples here](https://github.com/SODALITE-EU/image-builder/tree/master/REST_API/JSON-build-params)) and showing the result of the image building process (OK/failed - error msg accessible through image-builder endpoints). 
The user can build multiple images for the project at any time during AADM editing. The user can also trigger the same image building at different times. 

Image builder dockerhub image: `docker pull sodaliteh2020/image-builder-api:0.3.2` can be run with docker-compose.

Image builder returns results about the building process as described below. 

Full requests are available [here](https://github.com/SODALITE-EU/image-builder/blob/master/api-calls.http). More info about different build options can be found [here](https://github.com/SODALITE-EU/image-builder/blob/master/api-calls.http).

**Start build job**
Image building Job is requested using /build endpoint. Endpoint accepts the docker image building job and returns the session token.

``` sh
curl -X POST "[http or https]://[IP]:[PORT]/build/" -H "accept: application/json" -H "Content-Type: application/json" -d [DATA]
```
returns:
``` JSON
response_object = {
   "status": "Accepted",
   "message": "Successfully submitted docker image building job.",
   "session_token": "uuid-session-token"
}
```
and `status_code = 202`

**Check job status**
To check image building job status, users can use `session_token`, obtained from `/build` endpoint, and call `/info/status/{session_token}` endpoint:

``` 
curl -X GET "http://localhost:8080/info/status/[session_token]" -H "accept: application/json"
```
_2a: State building_

``` JSON
response_object = {
  "session_token": "uuid-session_token",
  "state": "building",
  "timestamp_start": "available in next version of image builder REST API"
}
```
with `status_code = 202`

_2b: State done_

``` JSON
response_object = {
  "session_token": "uuid-session-token",
  "state": "done",
  "timestamp_start": "2021-02-12T11:18:20.336601",
  "timestamp_end": "2021-02-12T11:18:27.132806"
}
```
returned with `status_code = 201`

_2c: State failed_
``` JSON
response_object = {
  "session_token": "uuid-session-token",
  "state": "failed",
  "timestamp_start": "2021-02-12T11:20:33.493011",
  "timestamp_end": "2021-02-12T11:20:33.861357"
}
```
returned with `status_code = 500`

**3 Check logs**
When state changes from `building` to `done` or `failed`, logs can be accessed with a call to `/info/log/{session_token}`.

``` sh
curl -X GET "http://localhost:8080/info/log/1575967c-f1c1-43a3-9b55-dce4520d4cd5" -H "accept: application/json"
3b: logs success
```
``` JSON
response_object = {
  "session_token": "uuid-session_token",
  "state": "done",
  "timestamp_start": "2021-02-12T11:20:33.493011",
  "timestamp_end": "2021-02-12T11:20:33.861357",
  "log": "..."
}
```
returned with `status_code = 200`

_4b: logs fail_

``` JSON
response_object = {
  "session_token": "uuid-session_token",
  "state": "failed",
  "timestamp_start": "2021-02-12T11:20:33.493011",
  "timestamp_end": "2021-02-12T11:20:33.861357",
  "log": "..log-info-here.."
}
```
returned with `status_code = 200`

_4c: logs not found_
``` JSON
response_object = {
  "status": "fail",
  "message": "Logfile not found."
}
```
returned with `status_code = 404`

**Comment by jesus-gorronogoitia** [comment]
@dradX should this image building process be done independently of the AADM deployment process? In current IDE version, the IDE call the process to create images from one build image configuration file, if provided by the user in the AADM deployment wizard. Should it be maintain within the deployment process and/or provide a separate process, described in this issue, to build the images?

**Comment by dradX** [comment]
@jesus-gorronogoitia Yes this process is independent of the AADM deployment process. The user can have multiple images (applications) he/she can deploy in a single AADM. So there can be multiple calls for image building for an AADM.

**Comment by jesus-gorronogoitia** [comment]
@dradX I guess this process is independent of the AADM being edited, that is, the current edited AADM is not an input of the image building process, so that this process can be initiated from the IDE without requiring having an AADM opened in the editor

**Comment by dradX** [comment]
@jesus-gorronogoitia It can be done even separately, but if we do it during AADM it can be stored in the KB and used for suggesting the image during the creation of the AADM.

**Comment by jesus-gorronogoitia** [comment]
Image building process support in IDE implement in commit https://github.com/SODALITE-EU/ide/commit/2e560739835b695aa96bac8dec4eb59e3e7c45a6
Not tested as no Image Builder instance is available

**Comment by jesus-gorronogoitia** [comment]
@dradX can this issue be closed?

**Comment by jesus-gorronogoitia** [comment]
closing solved issues. Could be reopened if needed
